import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`products\` ADD \`source\` text DEFAULT 'manual';`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`source_id\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`product_id\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`vendor_id\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`vendor_name\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`sales_page_url\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`affiliate_support_page_url\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`marketplace_image_url\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`accepts_affiliations_automatically\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`approval_status\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`billing_types\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`commission_fixed\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`conversion_rate\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`cancel_rate\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`earnings_per_sale\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`earnings_per_orderform_click\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`sales_rank\` numeric;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`source_status\` text DEFAULT 'active';`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`last_seen_at\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`source_data\` text;`)
  await db.run(sql`CREATE INDEX \`products_source_idx\` ON \`products\` (\`source\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`products_source_id_idx\` ON \`products\` (\`source_id\`);`)
  await db.run(sql`CREATE INDEX \`products_product_id_idx\` ON \`products\` (\`product_id\`);`)
  await db.run(sql`CREATE INDEX \`products_sales_rank_idx\` ON \`products\` (\`sales_rank\`);`)
  await db.run(sql`CREATE INDEX \`products_source_status_idx\` ON \`products\` (\`source_status\`);`)
  await db.run(sql`CREATE INDEX \`products_last_seen_at_idx\` ON \`products\` (\`last_seen_at\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`products_source_idx\`;`)
  await db.run(sql`DROP INDEX \`products_source_id_idx\`;`)
  await db.run(sql`DROP INDEX \`products_product_id_idx\`;`)
  await db.run(sql`DROP INDEX \`products_sales_rank_idx\`;`)
  await db.run(sql`DROP INDEX \`products_source_status_idx\`;`)
  await db.run(sql`DROP INDEX \`products_last_seen_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`source\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`source_id\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`product_id\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`vendor_id\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`vendor_name\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`sales_page_url\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`affiliate_support_page_url\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`marketplace_image_url\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`accepts_affiliations_automatically\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`approval_status\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`billing_types\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`commission_fixed\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`conversion_rate\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`cancel_rate\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`earnings_per_sale\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`earnings_per_orderform_click\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`sales_rank\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`source_status\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`last_seen_at\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`source_data\`;`)
}
